# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import warnings

import grpc
from proto.chat import message_pb2 as proto_dot_chat_dot_message__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/chat/message_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatMessageServiceStub(object):
    """─── Chat Message Service ────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_stream(
                '/oprai.chat.ChatMessageService/SendMessage',
                request_serializer=proto_dot_chat_dot_message__pb2.SendMessageRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_message__pb2.SendMessageResponse.FromString,
                _registered_method=True)
        self.GetMessages = channel.unary_unary(
                '/oprai.chat.ChatMessageService/GetMessages',
                request_serializer=proto_dot_chat_dot_message__pb2.GetMessagesRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_message__pb2.GetMessagesResponse.FromString,
                _registered_method=True)


class ChatMessageServiceServicer(object):
    """─── Chat Message Service ────────────────────────────────────────────────────

    """

    def SendMessage(self, request, context):
        """Send a user message and receive streaming assistant response tokens.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMessages(self, request, context):
        """Retrieve the message history for a session (paginated).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatMessageServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_stream_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=proto_dot_chat_dot_message__pb2.SendMessageRequest.FromString,
                    response_serializer=proto_dot_chat_dot_message__pb2.SendMessageResponse.SerializeToString,
            ),
            'GetMessages': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMessages,
                    request_deserializer=proto_dot_chat_dot_message__pb2.GetMessagesRequest.FromString,
                    response_serializer=proto_dot_chat_dot_message__pb2.GetMessagesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oprai.chat.ChatMessageService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oprai.chat.ChatMessageService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatMessageService(object):
    """─── Chat Message Service ────────────────────────────────────────────────────

    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/oprai.chat.ChatMessageService/SendMessage',
            proto_dot_chat_dot_message__pb2.SendMessageRequest.SerializeToString,
            proto_dot_chat_dot_message__pb2.SendMessageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetMessages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oprai.chat.ChatMessageService/GetMessages',
            proto_dot_chat_dot_message__pb2.GetMessagesRequest.SerializeToString,
            proto_dot_chat_dot_message__pb2.GetMessagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
