# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from proto.chat import session_pb2 as proto_dot_chat_dot_session__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in proto/chat/session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChatSessionServiceStub(object):
    """─── Chat Session Service ────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateSession = channel.unary_unary(
                '/oprai.chat.ChatSessionService/CreateSession',
                request_serializer=proto_dot_chat_dot_session__pb2.CreateSessionRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_session__pb2.SessionMeta.FromString,
                _registered_method=True)
        self.GetSession = channel.unary_unary(
                '/oprai.chat.ChatSessionService/GetSession',
                request_serializer=proto_dot_chat_dot_session__pb2.GetSessionRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_session__pb2.SessionMeta.FromString,
                _registered_method=True)
        self.ListSessions = channel.unary_unary(
                '/oprai.chat.ChatSessionService/ListSessions',
                request_serializer=proto_dot_chat_dot_session__pb2.ListSessionsRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_session__pb2.ListSessionsResponse.FromString,
                _registered_method=True)
        self.UpdateSessionTitle = channel.unary_unary(
                '/oprai.chat.ChatSessionService/UpdateSessionTitle',
                request_serializer=proto_dot_chat_dot_session__pb2.UpdateSessionTitleRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_session__pb2.SessionMeta.FromString,
                _registered_method=True)
        self.DeleteSession = channel.unary_unary(
                '/oprai.chat.ChatSessionService/DeleteSession',
                request_serializer=proto_dot_chat_dot_session__pb2.DeleteSessionRequest.SerializeToString,
                response_deserializer=proto_dot_chat_dot_session__pb2.DeleteSessionResponse.FromString,
                _registered_method=True)


class ChatSessionServiceServicer(object):
    """─── Chat Session Service ────────────────────────────────────────────────────

    """

    def CreateSession(self, request, context):
        """Create a new chat session for the authenticated wallet.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSession(self, request, context):
        """Retrieve a single session by ID.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListSessions(self, request, context):
        """List sessions for the authenticated wallet (paginated).
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSessionTitle(self, request, context):
        """Rename an existing session.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSession(self, request, context):
        """Soft-delete a session and all its messages.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatSessionServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateSession': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSession,
                    request_deserializer=proto_dot_chat_dot_session__pb2.CreateSessionRequest.FromString,
                    response_serializer=proto_dot_chat_dot_session__pb2.SessionMeta.SerializeToString,
            ),
            'GetSession': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSession,
                    request_deserializer=proto_dot_chat_dot_session__pb2.GetSessionRequest.FromString,
                    response_serializer=proto_dot_chat_dot_session__pb2.SessionMeta.SerializeToString,
            ),
            'ListSessions': grpc.unary_unary_rpc_method_handler(
                    servicer.ListSessions,
                    request_deserializer=proto_dot_chat_dot_session__pb2.ListSessionsRequest.FromString,
                    response_serializer=proto_dot_chat_dot_session__pb2.ListSessionsResponse.SerializeToString,
            ),
            'UpdateSessionTitle': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSessionTitle,
                    request_deserializer=proto_dot_chat_dot_session__pb2.UpdateSessionTitleRequest.FromString,
                    response_serializer=proto_dot_chat_dot_session__pb2.SessionMeta.SerializeToString,
            ),
            'DeleteSession': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSession,
                    request_deserializer=proto_dot_chat_dot_session__pb2.DeleteSessionRequest.FromString,
                    response_serializer=proto_dot_chat_dot_session__pb2.DeleteSessionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'oprai.chat.ChatSessionService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('oprai.chat.ChatSessionService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChatSessionService(object):
    """─── Chat Session Service ────────────────────────────────────────────────────

    """

    @staticmethod
    def CreateSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oprai.chat.ChatSessionService/CreateSession',
            proto_dot_chat_dot_session__pb2.CreateSessionRequest.SerializeToString,
            proto_dot_chat_dot_session__pb2.SessionMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oprai.chat.ChatSessionService/GetSession',
            proto_dot_chat_dot_session__pb2.GetSessionRequest.SerializeToString,
            proto_dot_chat_dot_session__pb2.SessionMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListSessions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oprai.chat.ChatSessionService/ListSessions',
            proto_dot_chat_dot_session__pb2.ListSessionsRequest.SerializeToString,
            proto_dot_chat_dot_session__pb2.ListSessionsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSessionTitle(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oprai.chat.ChatSessionService/UpdateSessionTitle',
            proto_dot_chat_dot_session__pb2.UpdateSessionTitleRequest.SerializeToString,
            proto_dot_chat_dot_session__pb2.SessionMeta.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSession(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/oprai.chat.ChatSessionService/DeleteSession',
            proto_dot_chat_dot_session__pb2.DeleteSessionRequest.SerializeToString,
            proto_dot_chat_dot_session__pb2.DeleteSessionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
