import { Injectable } from '@angular/core';
import type { ChatMessage } from './chat-api.service';

export interface ParsedAction {
  type: string;
  params: Record<string, string>;
  raw: string;
  /** Chain this action to the previous one's output.
   * E.g., swap output → stake input (jitoSOL)
   * When true, the output of previous action is used as input for this action. */
  chainFromPrevious?: boolean;
  /** Recipient address is not a known protocol — show a warning before user confirms. */
  warnUnverifiedDestination?: boolean;
}

export interface ParsedQuery {
  type: string;
  params: Record<string, string>;
  raw: string;
}

/** Single option — runs as ACTION immediately when clicked */
export interface ClarifyOption {
  label: string;
  sublabel?: string;
  action: string;
  params: Record<string, string>;
  /** A logo for THIS option, when the thing being chosen has one of its own —
   *  a validator, say. Without it the card fell back to matching the action
   *  prefix against the protocol registry, which gave a validator named
   *  "Drift" the Drift protocol's logo. */
  icon?: string;
}

/** [CLARIFY:type] block generated by LLM for protocol ambiguity */
export interface ParsedClarify {
  category: string;
  question: string;
  options: ClarifyOption[];
  raw: string;
}

export interface ParsedIntent {
  actions: ParsedAction[];
  queries: ParsedQuery[];
  clarifications: ParsedClarify[];
}

/**
 * The three per-message maps `MessageListComponent` consumes, keyed by
 * message id. Produced by {@link IntentParserService.parseHistory}.
 */
export interface ParsedHistory {
  actions: Map<string, ParsedAction[]>;
  queries: Map<string, ParsedQuery[]>;
  clarifications: Map<string, ParsedClarify[]>;
}

/**
 * Parses [ACTION:type] and [QUERY:type] blocks from assistant messages.
 *
 * Format: [ACTION:transfer] to=HwM... amount=1 token=SOL
 * Format: [QUERY:balance] wallet=self token=all
 *
 * Parameter values can be:
 * - Simple: key=value (no spaces)
 * - Quoted: key="value with spaces"
 * - Bracketed: key=<url://with-special/chars> (for URLs)
 * - JSON: [ACTION:type] {"key": "value", ...}  ← preferred new format
 * - [CLARIFY:category] {"question": "...", "options": [...]}
 */
/**
 * Complete whitelist of valid action types.
 * Any [ACTION:xxx] block not in this set is silently dropped.
 */
const KNOWN_ACTION_TYPES = new Set<string>([
  // Core Solana
  'transfer', 'swap', 'stake', 'unstake', 'burn', 'claim', 'vote',
  'launch_token', 'cross_chain_swap', 'bridge', 'uniswap_swap', 'uniswap_pools', 'uniswap_add_liquidity',
  'pools_buy', 'pools_sell', 'pools_launch',
  'pons_buy', 'pons_sell', 'pons_launch',
  // Morpho Blue lending (Robinhood Chain 4663 — EVM)
  'morpho_supply', 'morpho_borrow', 'morpho_repay', 'morpho_withdraw',
  // SushiSwap (Robinhood Chain 4663 — EVM)
  'sushi_swap', 'sushi_add_liquidity',
  'nft_buy', 'nft_list', 'nft_mint',
  // Jupiter
  'limit_order', 'cancel_limit_order', 'cancel_all_limit_orders', 'dca', 'cancel_dca',
  'jupsol_stake', 'jupsol_unstake',
  'lend', 'withdraw_lend', 'borrow', 'repay',
  'perp_open', 'perp_close', 'jlp_add', 'jlp_remove',
  // Lighter perps (Robinhood Chain domain — stock perps in USDG)
  'lighter_onboard', 'lighter_deposit', 'lighter_open', 'lighter_close', 'lighter_leverage',
  // pump.fun — bonding curve transactions
  'pumpfun_buy', 'pumpfun_sell', 'pumpfun_launch',
  // pump.fun — data queries
  'pumpfun_token_info', 'pumpfun_trending', 'pumpfun_new',
  'pumpfun_graduating', 'pumpfun_search', 'pumpfun_koth',
  'pumpfun_comments', 'pumpfun_user', 'pumpfun_bonding_curve',
  // PumpSwap AMM — graduated token transactions
  'pumpswap_buy', 'pumpswap_sell',
  // PumpSwap AMM — data queries
  'pumpswap_pool_info',
  // Jupiter — data queries
  'jup_dca_orders', 'jup_limit_orders', 'jup_price', 'jup_token_search',
  'jup_tokens_tag', 'jup_tokens_recent', 'jup_tokens_trending',
  'jup_portfolio_positions', 'jup_staked_jup',
  'jup_lend_positions', 'jup_lend_earnings', 'jup_pending_invites', 'jup_lend_markets', 'jup_platforms',
  // Helius
  'helius_tx_history', 'helius_parse_transactions',
  'helius_get_assets', 'helius_get_asset', 'helius_search_assets',
  'helius_nft_editions', 'helius_get_token_accounts', 'helius_asset_signatures',
  'helius_priority_fee', 'helius_wallet_identity', 'helius_batch_identity',
  'helius_wallet_balances', 'helius_wallet_history', 'helius_wallet_transfers', 'helius_wallet_funded_by',
  'helius_get_asset_batch', 'helius_get_assets_by_creator', 'helius_get_assets_by_authority', 'helius_get_assets_by_group',
  'helius_get_asset_proof', 'helius_get_asset_proof_batch',
  'helius_create_webhook', 'helius_list_webhooks', 'helius_get_webhook',
  'helius_update_webhook', 'helius_toggle_webhook', 'helius_delete_webhook',
  'helius_send_transaction',
  'helius_zk_compressed_account', 'helius_zk_multiple_compressed_accounts',
  'helius_zk_compressed_balance_by_owner', 'helius_zk_token_accounts_by_owner',
  'helius_zk_token_balances_by_owner', 'helius_zk_mint_token_holders',
  'helius_zk_compression_signatures_for_owner', 'helius_zk_transaction_with_compression',
  'helius_zk_indexer_health', 'helius_zk_indexer_slot',
  'helius_zk_validity_proof', 'helius_zk_new_address_proofs',
  'helius_smart_send',
  // Raydium
  'raydium_swap', 'raydium_add_liquidity', 'raydium_remove_liquidity',
  'raydium_create_pool', 'raydium_open_position', 'raydium_close_position',
  'raydium_increase_position', 'raydium_decrease_position',
  // Raydium — data queries
  'raydium_get_pools', 'raydium_search_pools', 'raydium_swap_quote',
  'raydium_get_pool_info', 'raydium_get_user_positions', 'raydium_get_clmm_positions',
  'raydium_get_token_info', 'raydium_get_platform_stats', 'raydium_get_clmm_configs',
  'raydium_get_pools_by_lp', 'raydium_get_pools_v2', 'raydium_get_pool_keys',
  'raydium_get_pool_liquidity_history', 'raydium_get_pool_position_history',
  'raydium_get_token_list', 'raydium_get_token_prices',
  'raydium_get_farm_info', 'raydium_get_farm_by_lp', 'raydium_get_farm_keys',
  'raydium_get_ido_keys', 'raydium_get_main_version', 'raydium_get_rpcs',
  'raydium_get_chain_time', 'raydium_get_stake_pools', 'raydium_get_migrate_lp',
  'raydium_get_auto_fee', 'raydium_get_cpmm_configs',
  // Orca
  'orca_swap', 'orca_add_liquidity', 'orca_remove_liquidity',
  'orca_open_position', 'orca_close_position', 'orca_increase_position',
  'orca_decrease_position', 'orca_collect_fees', 'orca_collect_rewards',
  // Orca — pool creation + data queries
  'orca_create_pool',
  'orca_get_pools', 'orca_search_pools', 'orca_get_pool', 'orca_get_locked_liquidity',
  'orca_get_protocol_stats', 'orca_get_orca_token',
  'orca_get_circulating_supply', 'orca_get_total_supply',
  'orca_get_tokens', 'orca_search_tokens', 'orca_get_token',
  'orca_get_user_positions', 'orca_get_pool_positions',
  // Meteora — legacy actions
  'meteora_swap', 'meteora_add_liquidity', 'meteora_remove_liquidity',
  'meteora_create_pool', 'meteora_open_position', 'meteora_close_position',
  'meteora_add_to_position', 'meteora_claim_fees', 'meteora_claim_rewards',
  'meteora_stake', 'meteora_unstake', 'meteora_harvest',
  // Meteora — DLMM data queries
  'meteora_dlmm_get_pairs', 'meteora_dlmm_get_pair',
  'meteora_dlmm_get_user_positions', 'meteora_dlmm_get_active_bin',
  // Meteora — DAMM v2 queries + TX
  'meteora_dammv2_get_pools', 'meteora_dammv2_get_pool_groups',
  'meteora_dammv2_get_pool_group', 'meteora_dammv2_get_pool',
  'meteora_dammv2_get_pool_ohlcv', 'meteora_dammv2_get_pool_volume_history',
  'meteora_dammv2_get_protocol_metrics',
  'meteora_dammv2_swap', 'meteora_dammv2_add_liquidity', 'meteora_dammv2_remove_liquidity',
  'meteora_dammv2_claim_fee', 'meteora_dammv2_close_position',
  'meteora_dammv2_get_user_positions',
  // Meteora — DAMM v1 queries + TX
  'meteora_dammv1_get_pools', 'meteora_dammv1_get_pool_configs',
  'meteora_dammv1_search_pools', 'meteora_dammv1_get_farms',
  'meteora_dammv1_get_pools_metrics', 'meteora_dammv1_get_alpha_vaults',
  'meteora_dammv1_get_alpha_vault_configs', 'meteora_dammv1_get_pools_by_vault_lp',
  'meteora_dammv1_get_fee_config',
  'meteora_dammv1_swap', 'meteora_dammv1_deposit', 'meteora_dammv1_withdraw',
  // Meteora — Dynamic Vault queries + TX
  'meteora_vault_get_info', 'meteora_vault_get_addresses',
  'meteora_vault_get_state', 'meteora_vault_get_apy',
  'meteora_vault_get_apy_history', 'meteora_vault_get_virtual_price',
  'meteora_vault_deposit', 'meteora_vault_withdraw',
  // Meteora — Stake2Earn (m3m3) queries + TX
  'meteora_s2e_get_analytics', 'meteora_s2e_get_all_vaults',
  'meteora_s2e_filter_vaults', 'meteora_s2e_get_vault',
  'meteora_s2e_stake', 'meteora_s2e_unstake', 'meteora_s2e_claim_fee',
  'meteora_s2e_cancel_unstake', 'meteora_s2e_withdraw',
  // Kamino
  'kamino_deposit', 'kamino_withdraw', 'kamino_borrow', 'kamino_repay',
  'kamino_add_collateral', 'kamino_withdraw_collateral',
  'kamino_multiply_open', 'kamino_multiply_add', 'kamino_multiply_withdraw', 'kamino_multiply_close',
  'kamino_long_open', 'kamino_short_open', 'kamino_position_close',
  'kamino_vault_deposit', 'kamino_vault_withdraw', 'kamino_stake', 'kamino_unstake',
  'kamino_liquidity_deposit', 'kamino_liquidity_withdraw',
  // Kamino — data queries
  'kamino_liquidity_strategies',
  'kamino_vaults', 'kamino_markets', 'kamino_market_reserves',
  'kamino_user_vault_positions', 'kamino_user_obligations', 'kamino_oracle_prices', 'kamino_usd_benchmark_rates',
  'kamino_market_metrics_history', 'kamino_reserve_borrow_apy_history', 'kamino_reserve_borrow_apy_median',
  'kamino_obligation_interest_earned', 'kamino_obligation_interest_paid',
  // Kamino — K-Lend transactions + borrow orders
  'kamino_obligation_transactions', 'kamino_user_klend_transactions_all', 'kamino_user_klend_transactions',
  'kamino_borrow_order_fills', 'kamino_open_borrow_orders',
  // Kamino — yields + airdrop + staking
  'kamino_yield_history', 'kamino_principal_token_yields',
  'kamino_airdrop_allocations', 'kamino_airdrop_metrics',
  'kamino_staking_yields', 'kamino_staking_yields_median', 'kamino_staking_yields_mean',
  'kamino_user_staking_boosts', 'kamino_season_rewards_user', 'kamino_season_rewards_vesting_pool',
  'kamino_private_credit_metrics', 'kamino_private_credit_metrics_history',
  'kamino_user_farm_transactions', 'kamino_farm_transactions',
  // Kamino — extended earn vault data
  'kamino_vault_detail', 'kamino_vault_metrics', 'kamino_vault_metrics_history',
  'kamino_vault_allocation_history', 'kamino_vaults_rewards', 'kamino_vaults_summary',
  'kamino_vault_mint_metadata', 'kamino_vault_mint_image',
  // Kamino — extended earn user data
  'kamino_user_metrics_history', 'kamino_user_transactions', 'kamino_user_kvault_rewards', 'kamino_vault_transactions',
  'kamino_user_vault_position',
  'kamino_user_vault_metrics_history', 'kamino_user_vault_pnl', 'kamino_user_vault_pnl_history',
  // Kamino — vault action instructions
  'kamino_vault_deposit_instructions', 'kamino_vault_withdraw_instructions',
  // Kamino — extended borrow market data
  'kamino_market_detail', 'kamino_market_reserve_history',
  'kamino_market_leverage_metrics', 'kamino_market_reserves_account',
  // Kamino — extended borrow user/loan data
  'kamino_user_rewards', 'kamino_loan_detail', 'kamino_obligation_pnl',
  'kamino_obligation_metrics_history', 'kamino_rewards_list', 'kamino_rewards_history',
  // Kamino — borrow/repay instruction variants
  'kamino_borrow_instructions', 'kamino_repay_instructions',
  // Kamino — KSwap
  'kamino_kswap',
  // Kamino — K-Lend deposit/withdraw instruction variants
  'kamino_deposit_instructions', 'kamino_withdraw_instructions',
  // Jito
  'jito_stake', 'jito_unstake', 'jito_tip', 'jito_bundle', 'jito_bundle_status',
  // Marinade
  'marinade_stake', 'marinade_unstake', 'marinade_delayed_unstake', 'marinade_claim_ticket', 'marinade_claim',
  // Solend (data-only — transactional ops not supported)
  'solend_user_info', 'solend_reserves', 'solend_market',
  // Streamflow — token streaming / vesting (full SDK)
  'streamflow_create', 'streamflow_create_multiple', 'streamflow_cancel',
  'streamflow_withdraw', 'streamflow_transfer', 'streamflow_topup',
  'streamflow_update', 'streamflow_get_one', 'streamflow_list',
  // Cross-chain bridges — Squid v2 full action set
  'debridge', 'squid', 'squid_bridge', 'squid_status',
  // Cross-chain bridges — Relay.link full action set (default cross-chain provider)
  'relay_bridge', 'relay_index_transaction', 'relay_single_transaction',
  'relay_deposit_address_reindex', 'relay_claim_app_fees',
  'relay_fast_fill', 'relay_execute',
  // Solana Name Service (SNS) — .sol domain transactions
  'sns_register', 'sns_transfer', 'sns_set_record', 'sns_delete',
  'sns_create_subdomain', 'sns_list', 'sns_buy',
  'sns_make_offer', 'sns_accept_offer', 'sns_cancel_offer',
  'sns_set_favorite', 'sns_transfer_subdomain',
]);

/**
 * Complete whitelist of valid query types.
 * Any [QUERY:xxx] block not in this set is silently dropped.
 */
const KNOWN_QUERY_TYPES = new Set<string>([
  // Core queries
  'balance', 'price', 'portfolio', 'positions', 'transactions',
  'token_info', 'trending', 'network', 'risk', 'yield',
  'analytics', 'nft_collection', 'airdrops', 'gas',
  'wallet_info', 'tax_report', 'limit_orders', 'dca', 'lend_positions', 'perp_positions',
  'lighter_positions', 'lighter_markets', 'lighter_market',
  // Morpho Blue lending (Robinhood Chain) — market list + user positions cards
  'morpho_markets', 'morpho_positions',
  // SushiSwap (Robinhood Chain) — pool list card
  'sushi_pools',
  // Kamino Multiply pool list (self-fetching query-card)
  'kamino_multiply_markets',
  // Simulation & tracking
  'simulate', 'whale', 'smart_money',
  // SNS — Solana Name Service queries
  'sns_resolve', 'sns_reverse_lookup', 'sns_domains', 'sns_record',
  'sns_domain_info', 'sns_check_available', 'sns_primary_domain', 'sns_subdomains',
  'sns_twitter_handle',
  // Uniswap LP pool listing (self-fetching query-card, EVM)
  'uniswap_pools',
  // Cross-chain queries
  'cross_chain_quote', 'cross_chain_chains', 'cross_chain_tokens',
  // Relay.link queries — quotes, chains, tokens, history, status
  'relay_get_quote', 'relay_get_chains', 'relay_get_chains_liquidity',
  'relay_get_currencies', 'relay_get_token_price', 'relay_get_requests',
  'relay_intent_status', 'relay_get_app_fee_balances', 'relay_get_swap_sources',
]);

@Injectable({ providedIn: 'root' })
export class IntentParserService {
  // Legacy key=value format
  private readonly ACTION_REGEX =
    /\[ACTION:(\w+)\]\s*((?:\w+=(?:<[^>]+>|"[^"]+"|\S+)\s*)*)/gi;

  // New JSON format: [ACTION:type] {...}
  private readonly ACTION_JSON_REGEX =
    /\[ACTION:(\w+)\]\s*(\{[^}]*(?:\{[^}]*\}[^}]*)?\})/gi;

  private readonly QUERY_REGEX =
    /\[QUERY:(\w+)\]\s*((?:\w+=(?:<[^>]+>|"[^"]+"|\S+)\s*)*)/gi;

  /**
   * Parse all action, query and clarify blocks from a message string
   */
  parseAll(content: string): ParsedIntent {
    return {
      actions: this.parse(content),
      queries: this.parseQueries(content),
      clarifications: this.parseClarifications(content),
    };
  }

  /**
   * Parse action blocks from a message string.
   *
   * Security note: the legacy key=value format ([ACTION:type] key=value …) is
   * disabled by default. The backend now uses OpenAI function calling exclusively
   * and emits structured SSE events — text-based action blocks in assistant messages
   * are a sign of jailbreak-induced output. Only the JSON format is accepted here,
   * and only for backward-compatible rendering of messages stored before the
   * function-calling migration. Pass legacyMode=true only for explicitly old messages.
   */
  parse(content: string, legacyMode = false): ParsedAction[] {
    if (!content) return [];

    const seen = new Set<string>();
    const actions: ParsedAction[] = [];
    let match: RegExpExecArray | null;

    // JSON format: [ACTION:type] {...}
    this.ACTION_JSON_REGEX.lastIndex = 0;
    while ((match = this.ACTION_JSON_REGEX.exec(content)) !== null) {
      const type = match[1].toLowerCase();
      const jsonStr = match[2].trim();
      const raw = match[0];

      if (seen.has(raw)) continue;
      seen.add(raw);

      const params = this.parseJsonParams(jsonStr);
      if (KNOWN_ACTION_TYPES.has(type)) {
        const chainFromPrevious = params['chain'] === 'true' || params['chain'] === '1';
        const { chain, ...actionParams } = params;
        actions.push({ type, params: actionParams, raw, chainFromPrevious });
      }
    }

    // Legacy key=value format — disabled by default to prevent jailbreak-induced
    // text blocks from being parsed as executable actions.
    if (legacyMode) {
      this.ACTION_REGEX.lastIndex = 0;
      while ((match = this.ACTION_REGEX.exec(content)) !== null) {
        const raw = match[0];
        if (seen.has(raw)) continue;
        const matchStart = match.index;
        const isJsonBlock = /^\s*\[ACTION:\w+\]\s*\{/.test(content.substring(matchStart));
        if (isJsonBlock) { seen.add(raw); continue; }
        seen.add(raw);
        const type = match[1].toLowerCase();
        if (!KNOWN_ACTION_TYPES.has(type)) continue;
        const params = this.parseParams(match[2].trim());
        const chainFromPrevious = params['chain'] === 'true' || params['chain'] === '1';
        const { chain, ...actionParams } = params;
        actions.push({ type, params: actionParams, raw, chainFromPrevious });
      }
    }

    return actions;
  }

  /**
   * Parse [CLARIFY:category] blocks for protocol disambiguation
   */
  parseClarifications(content: string): ParsedClarify[] {
    if (!content) return [];

    const clarifications: ParsedClarify[] = [];
    // Greedy JSON extraction for CLARIFY blocks — supports nested {}
    const clarifyPattern = /\[CLARIFY:(\w+)\]\s*(\{)/g;
    let m: RegExpExecArray | null;

    while ((m = clarifyPattern.exec(content)) !== null) {
      const category = m[1].toLowerCase();
      const start = m.index + m[0].length - 1; // { karakterinin indeksi
      const jsonStr = this.extractBalancedJson(content, start);
      if (!jsonStr) continue;

      try {
        const data = JSON.parse(jsonStr);
        const raw = `[CLARIFY:${m[1]}] ${jsonStr}`;
        // Filter out options whose action is not in the whitelist (defence-in-depth)
        const validOptions = (data.options ?? [])
          .filter((o: any) => typeof o.action === 'string' && KNOWN_ACTION_TYPES.has(o.action.toLowerCase()))
          .map((o: any) => ({
            label: o.label ?? '',
            sublabel: o.sublabel,
            // Dropped here, the icon never reached the card no matter how many
            // layers upstream carried it.
            icon: typeof o.icon === 'string' ? o.icon : undefined,
            action: (o.action as string).toLowerCase(),
            params: this.normalizeToStringRecord(o.params ?? {}),
          }));
        if (validOptions.length === 0) continue; // drop entire clarify if no valid options
        clarifications.push({
          category,
          question: data.question ?? '',
          options: validOptions,
          raw,
        });
      } catch {
        // Invalid JSON — skip
      }
    }

    return clarifications;
  }

  /**
   * Parse all query blocks from a message string
   */
  parseQueries(content: string): ParsedQuery[] {
    if (!content) return [];

    const queries: ParsedQuery[] = [];
    let match: RegExpExecArray | null;

    this.QUERY_REGEX.lastIndex = 0;

    while ((match = this.QUERY_REGEX.exec(content)) !== null) {
      const type = match[1].toLowerCase();
      if (!KNOWN_QUERY_TYPES.has(type)) continue; // Skip unknown query types

      const paramsStr = match[2].trim();
      const params = this.parseParams(paramsStr);

      queries.push({
        type: this.redirectProtocolPositions(type, params),
        params,
        raw: match[0],
      });
    }

    return queries;
  }

  /**
   * `positions protocol=<x>` is the generic cross-protocol card: it reads the
   * portfolio aggregate, which knows nothing about DLMM bins, per-position
   * ranges or unclaimed fees. When the user asked about ONE protocol that has
   * its own positions card, that dedicated card is always the better answer —
   * so rewrite the type here rather than trusting the model to pick it. Doing
   * it at parse time fixes the label, the icon, the fetch and the template
   * gate in one place, since all four switch on `query.type`.
   */
  private redirectProtocolPositions(type: string, params: Record<string, string>): string {
    if (type !== 'positions') return type;
    const p = (params['protocol'] ?? '').toLowerCase();
    if (!p) return type;
    if (p.includes('dlmm') || p.includes('meteora')) return 'meteora_dlmm_get_user_positions';
    if (p.includes('raydium')) return 'raydium_get_user_positions';
    if (p.includes('orca')) return 'orca_get_user_positions';
    return type;
  }

  /**
   * Check if a message contains any action blocks
   */
  /**
   * Rebuild the action / query / clarify cards for a loaded conversation.
   *
   * Structured intent from the backend's function calling (`metadata.actions`
   * and friends) always wins; text parsing is only the fallback for messages
   * stored before that migration. Every surface that renders a stored
   * conversation — the chat shell and the search preview — must go through
   * this method, or the two drift and the same history renders differently
   * depending on where you look at it.
   */
  parseHistory(messages: readonly ChatMessage[] | null | undefined): ParsedHistory {
    const actions = new Map<string, ParsedAction[]>();
    const queries = new Map<string, ParsedQuery[]>();
    const clarifications = new Map<string, ParsedClarify[]>();

    for (const msg of messages ?? []) {
      if (msg.role !== 'assistant') continue;
      const meta = msg.metadata;

      const structuredActions = meta?.actions;
      const structuredQueries = meta?.queries;
      const structuredClarifications = meta?.clarifications;

      if (structuredActions?.length) {
        actions.set(msg.id, structuredActions.map(a => ({
          type: a.type, params: a.params, raw: '',
          chainFromPrevious: a.chainFromPrevious ?? false,
          warnUnverifiedDestination: a.warnUnverifiedDestination ?? false,
        })));
      }
      if (structuredQueries?.length) {
        queries.set(msg.id, structuredQueries.map(q => ({
          type: q.type, params: q.params, raw: '',
        })));
      }
      if (structuredClarifications?.length) {
        clarifications.set(msg.id, structuredClarifications.map(c => ({
          category: c.category, question: c.question,
          options: c.options.map(o => ({
            label: o.label, sublabel: o.sublabel, icon: o.icon,
            action: o.action, params: o.params,
          })),
          raw: '',
        })));
      }

      if (!structuredActions?.length && !structuredQueries?.length && !structuredClarifications?.length) {
        const parsed = this.parseAll(msg.content);
        if (parsed.actions.length > 0) actions.set(msg.id, parsed.actions);
        if (parsed.queries.length > 0) queries.set(msg.id, parsed.queries);
        if (parsed.clarifications.length > 0) clarifications.set(msg.id, parsed.clarifications);
      }
    }

    return { actions, queries, clarifications };
  }

  hasActions(content: string): boolean {
    this.ACTION_REGEX.lastIndex = 0;
    return this.ACTION_REGEX.test(content);
  }

  /**
   * Check if a message contains any query blocks
   */
  hasQueries(content: string): boolean {
    this.QUERY_REGEX.lastIndex = 0;
    return this.QUERY_REGEX.test(content);
  }

  /**
   * Check if a message contains any action or query blocks
   */
  hasIntents(content: string): boolean {
    return this.hasActions(content) || this.hasQueries(content);
  }

  /**
   * Remove action and query blocks from content (for display without raw blocks)
   */
  stripActions(content: string): string {
    // JSON action format: [ACTION:type] {...}
    const jsonActionPattern = /\[ACTION:\w+\]\s*\{[^}]*(?:\{[^}]*\}[^}]*)?\}/g;
    // CLARIFY blocks (greedy, handles nested {})
    const clarifyPattern = /\[CLARIFY:\w+\]\s*\{[\s\S]*?\}(?=\s*(?:\[|$))/g;

    return content
      .replace(jsonActionPattern, '')
      .replace(clarifyPattern, '')
      .replace(this.ACTION_REGEX, '')
      .replace(this.QUERY_REGEX, '')
      .trim();
  }

  /**
   * Get a human-readable label for an action type
   */
  getActionLabel(action: ParsedAction): string {
    switch (action.type) {
      case 'transfer':
        return `Transfer ${action.params['amount'] ?? ''} ${action.params['token'] ?? 'SOL'}`;
      case 'swap':
        return `Swap ${action.params['amount'] ?? ''} ${action.params['inputMint'] ?? ''} → ${action.params['outputMint'] ?? ''}`;
      case 'stake':
        return `Stake ${action.params['amount'] ?? ''} SOL on ${action.params['protocol'] ?? 'native'}`;
      case 'unstake':
        return `Unstake ${action.params['amount'] ?? ''} from ${action.params['protocol'] ?? 'native'}`;
      case 'provide_liquidity':
        return `Add Liquidity to pool`;
      case 'remove_liquidity':
        return `Remove Liquidity`;
      case 'dca':
        return `DCA ${action.params['totalAmount'] ?? action.params['amount'] ?? ''} ${action.params['inputMint'] ?? ''} → ${action.params['outputMint'] ?? ''} ×${action.params['numberOfOrders'] ?? ''} (${action.params['frequency'] ?? action.params['intervalSeconds'] ?? ''})`;
      case 'cancel_dca': {
        const dcaOrder = String(action.params['order'] ?? '');
        const isAuto = !dcaOrder || ['self', 'all', 'auto', 'mine', 'active'].includes(dcaOrder.toLowerCase());
        return isAuto ? 'Cancel DCA order' : `Cancel DCA order ${dcaOrder.slice(0, 8)}...`;
      }
      case 'limit_order':
        return `Limit Order: ${action.params['amount'] ?? ''} ${action.params['inputMint'] ?? ''} at $${action.params['targetPrice'] ?? ''}`;
      case 'cancel_limit_order':
        return `Cancel Limit Order ${(action.params['order'] ?? '').slice(0, 8)}...`;
      case 'cancel_all_limit_orders':
        return 'Cancel All Limit Orders';
      case 'jupsol_stake':
        return `Stake ${action.params['amount'] ?? ''} SOL → jupSOL (Jupiter Liquid Staking)`;
      case 'jupsol_unstake':
        return `Unstake ${action.params['amount'] ?? ''} jupSOL → SOL`;
      case 'lend':
        return `Deposit ${action.params['amount'] ?? ''} ${action.params['token'] ?? ''} into Jupiter Lend`;
      case 'withdraw_lend':
        return `Withdraw ${action.params['amount'] ?? ''} ${action.params['token'] ?? ''} from Jupiter Lend`;
      case 'borrow':
        return `Borrow ${action.params['amount'] ?? ''} ${action.params['token'] ?? ''} on Jupiter Lend`;
      case 'repay':
        return `Repay ${action.params['amount'] ?? ''} ${action.params['token'] ?? ''} on Jupiter Lend`;
      case 'perp_open':
        return `Open ${action.params['side'] ?? 'long'} ${action.params['market'] ?? 'SOL'} position ($${action.params['sizeUsd'] ?? ''})`;
      case 'perp_close':
        return `Close ${action.params['side'] ?? 'long'} ${action.params['market'] ?? 'SOL'} position`;
      case 'lighter_onboard':
        return `Enable Lighter perps trading`;
      case 'lighter_deposit':
        return `Deposit ${action.params['amount'] ?? ''} USDC to Lighter`;
      case 'lighter_open':
        return `Open ${action.params['side'] ?? 'long'} ${action.params['symbol'] ?? action.params['market'] ?? ''} on Lighter ($${action.params['collateralUsd'] ?? action.params['sizeUsd'] ?? ''})`;
      case 'lighter_close':
        return `Close ${action.params['side'] ?? ''} ${action.params['symbol'] ?? action.params['market'] ?? ''} on Lighter`;
      case 'lighter_leverage':
        return `Set ${action.params['symbol'] ?? ''} leverage to ${action.params['leverage'] ?? ''}x on Lighter`;
      case 'morpho_supply':
        return `Lend ${action.params['amount'] ?? ''} ${action.params['loanSymbol'] ?? 'USDG'} on Morpho`;
      case 'morpho_borrow':
        return `Borrow ${action.params['borrowAmount'] ?? ''} ${action.params['loanSymbol'] ?? 'USDG'} on Morpho`;
      case 'morpho_repay':
        return action.params['max'] === 'true' ? `Repay all on Morpho` : `Repay ${action.params['amount'] ?? ''} on Morpho`;
      case 'morpho_withdraw':
        return `Withdraw ${action.params['target'] === 'collateral' ? 'collateral' : 'supply'} on Morpho`;
      case 'sushi_swap':
        return `Swap on Sushi`;
      case 'sushi_add_liquidity':
        return `Add liquidity on Sushi`;
      case 'jlp_add':
        return `Add ${action.params['amount'] ?? ''} ${action.params['token'] ?? 'SOL'} to JLP pool`;
      case 'jlp_remove':
        return `Remove liquidity from JLP pool`;
      case 'nft_buy':
        return `Buy NFT on ${action.params['marketplace'] ?? 'marketplace'}`;
      case 'nft_list':
        return `List NFT for ${action.params['price'] ?? ''} SOL`;
      case 'burn':
        return `Burn ${action.params['amount'] ?? ''} ${action.params['token'] ?? 'tokens'}`;
      case 'claim':
        return `Claim ${action.params['type'] ?? 'rewards'} from ${action.params['protocol'] ?? ''}`;
      case 'nft_mint':
        return `Mint NFT: ${action.params['name'] ?? 'Untitled'}`;
      // ── SNS Actions ──────────────────────────────────────────────────────────
      case 'sns_register':
        return `Register ${action.params['domain'] ?? ''}.sol`;
      case 'sns_transfer':
        return `Transfer ${action.params['domain'] ?? ''}.sol to ${(action.params['newOwner'] as string)?.slice(0, 8) ?? ''}`;
      case 'sns_set_record':
        return `Set ${action.params['domain'] ?? ''}.sol [${action.params['record'] ?? ''}]`;
      case 'sns_delete':
        return `Delete ${action.params['domain'] ?? ''}.sol`;
      case 'sns_create_subdomain':
        return `Create subdomain ${action.params['subdomain'] ?? ''}.sol`;
      case 'sns_list':
        return `List ${action.params['domain'] ?? ''}.sol for ${action.params['price'] ?? ''} ${action.params['token'] ?? 'USDC'}`;
      case 'sns_buy':
        return `Buy ${action.params['domain'] ?? ''}.sol`;
      case 'sns_make_offer':
        return `Offer ${action.params['amount'] ?? ''} ${action.params['token'] ?? 'USDC'} for ${action.params['domain'] ?? ''}.sol`;
      case 'sns_accept_offer':
        return `Accept offer for ${action.params['domain'] ?? ''}.sol`;
      case 'sns_cancel_offer':
        return `Cancel offer for ${action.params['domain'] ?? ''}.sol`;
      case 'sns_p2p_create':
        return `P2P domain swap offer`;
      case 'sns_p2p_accept':
        return `Accept P2P domain swap`;
      case 'sns_p2p_cancel':
        return `Cancel P2P domain swap`;
      case 'sns_set_favorite':
        return `Set ${action.params['domain'] ?? ''}.sol as primary domain`;
      case 'sns_realloc':
        return `Expand ${action.params['domain'] ?? ''}.sol storage to ${action.params['newSpace'] ?? ''}B`;
      case 'sns_transfer_subdomain':
        return `Transfer subdomain ${action.params['subdomain'] ?? ''}`;
      case 'sns_create_record':
        return `Create ${action.params['record'] ?? ''} record for ${action.params['domain'] ?? ''}.sol`;
      case 'vote':
        return `Vote ${action.params['choice'] ?? ''} on ${action.params['protocol'] ?? ''} proposal`;
      case 'bridge':
        return `Bridge ${action.params['amount'] ?? ''} ${action.params['token'] ?? ''} from ${action.params['fromChain'] ?? ''} to ${action.params['toChain'] ?? ''}`;
      // ── Kamino Finance Actions ─────────────────────────────────────────────────
      case 'kamino_deposit':
        return `Deposit ${action.params['amount'] ?? ''} to Kamino Lend`;
      case 'kamino_withdraw':
        return `Withdraw ${action.params['amount'] ?? ''} from Kamino Lend`;
      case 'kamino_borrow':
        return `Borrow ${action.params['amount'] ?? ''} on Kamino Lend`;
      case 'kamino_repay':
        return `Repay ${action.params['amount'] ?? ''} on Kamino Lend`;
      case 'kamino_add_collateral':
        return `Add ${action.params['amount'] ?? ''} collateral on Kamino`;
      case 'kamino_withdraw_collateral':
        return `Withdraw ${action.params['amount'] ?? ''} collateral from Kamino`;
      case 'kamino_multiply_open':
        return `Open ${action.params['leverage'] ?? '2'}x multiply position on Kamino`;
      case 'kamino_multiply_add':
        return `Add ${action.params['amount'] ?? ''} to Kamino multiply position`;
      case 'kamino_multiply_withdraw':
        return `Withdraw ${action.params['amount'] ?? ''} from Kamino multiply position`;
      case 'kamino_multiply_close':
        return `Close Kamino multiply position`;
      case 'kamino_long_open':
        return `Open ${action.params['leverage'] ?? '2'}x long position on Kamino`;
      case 'kamino_short_open':
        return `Open ${action.params['leverage'] ?? '2'}x short position on Kamino`;
      case 'kamino_position_close':
        return `Close Kamino leveraged position`;
      case 'kamino_vault_deposit':
        return `Deposit to Kamino Liquidity Vault`;
      case 'kamino_vault_withdraw':
        return `Withdraw from Kamino Liquidity Vault`;
      case 'kamino_stake':
        return `Stake ${action.params['amount'] ?? ''} KMNO on Kamino`;
      case 'kamino_unstake':
        return `Unstake ${action.params['amount'] ?? ''} KMNO from Kamino`;
      case 'kamino_vaults':
        return `Kamino Earn vaults list`;
      case 'kamino_markets':
        return `Kamino K-Lend markets list`;
      case 'kamino_market_reserves':
        return `Kamino K-Lend market reserves`;
      case 'kamino_user_vault_positions':
        return `Kamino Earn vault positions`;
      case 'kamino_user_obligations':
        return `Kamino K-Lend obligations`;
      case 'kamino_oracle_prices':
        return `Kamino oracle prices`;
      case 'kamino_usd_benchmark_rates':
        return `USD benchmark lending rates`;
      case 'kamino_market_metrics_history':
        return `Kamino market metrics history`;
      case 'kamino_reserve_borrow_apy_history':
        return `Kamino reserve borrow APY history`;
      case 'kamino_reserve_borrow_apy_median':
        return `Kamino reserve borrow APY median`;
      case 'kamino_obligation_interest_earned':
        return `Kamino obligation interest earned`;
      case 'kamino_obligation_interest_paid':
        return `Kamino obligation interest paid`;
      case 'kamino_obligation_transactions':
        return `Kamino obligation transactions`;
      case 'kamino_user_klend_transactions_all':
        return `Kamino K-Lend transactions (all markets)`;
      case 'kamino_user_klend_transactions':
        return `Kamino K-Lend transactions`;
      case 'kamino_borrow_order_fills':
        return `Kamino borrow order fills`;
      case 'kamino_open_borrow_orders':
        return `Kamino open borrow orders`;
      case 'kamino_yield_history':
        return `Kamino yield history`;
      case 'kamino_principal_token_yields':
        return `Kamino principal token yields`;
      case 'kamino_airdrop_allocations':
        return `Kamino airdrop allocations`;
      case 'kamino_airdrop_metrics':
        return `Kamino airdrop metrics`;
      case 'kamino_staking_yields':
        return `Kamino staking yields`;
      case 'kamino_staking_yields_median':
        return `Kamino staking yields (median)`;
      case 'kamino_staking_yields_mean':
        return `Kamino staking yields (mean)`;
      case 'kamino_user_staking_boosts':
        return `Kamino user staking boosts`;
      case 'kamino_season_rewards_user':
        return `Kamino season rewards`;
      case 'kamino_season_rewards_vesting_pool':
        return `Kamino season rewards vesting pool`;
      case 'kamino_private_credit_metrics':
        return `Kamino private credit metrics`;
      case 'kamino_private_credit_metrics_history':
        return `Kamino private credit metrics history`;
      case 'kamino_user_farm_transactions':
        return `Kamino user farm transactions`;
      case 'kamino_farm_transactions':
        return `Kamino farm transactions`;
      case 'kamino_vault_detail':
        return `Kamino Earn vault details`;
      case 'kamino_vault_metrics':
        return `Kamino Earn vault metrics`;
      case 'kamino_vault_metrics_history':
        return `Kamino Earn vault metrics history`;
      case 'kamino_vault_allocation_history':
        return `Kamino Earn vault allocation history`;
      case 'kamino_vaults_rewards':
        return `Kamino Earn vaults rewards`;
      case 'kamino_vaults_summary':
        return `Kamino Earn vaults summary`;
      case 'kamino_vault_mint_metadata':
        return `Kamino kToken metadata`;
      case 'kamino_vault_mint_image':
        return `Kamino kToken image`;
      case 'kamino_user_metrics_history':
        return `Kamino user Earn metrics history`;
      case 'kamino_user_transactions':
        return `Kamino user Earn transactions`;
      case 'kamino_user_kvault_rewards':
        return `Kamino KVault season rewards`;
      case 'kamino_vault_transactions':
        return `Kamino vault transactions`;
      case 'kamino_user_vault_position':
        return `Kamino user vault position`;
      case 'kamino_user_vault_metrics_history':
        return `Kamino user vault metrics history`;
      case 'kamino_user_vault_pnl':
        return `Kamino user vault PnL`;
      case 'kamino_user_vault_pnl_history':
        return `Kamino user vault PnL history`;
      case 'kamino_vault_deposit_instructions':
        return `Kamino vault deposit instructions`;
      case 'kamino_vault_withdraw_instructions':
        return `Kamino vault withdraw instructions`;
      case 'kamino_market_detail':
        return `Kamino K-Lend market details`;
      case 'kamino_market_reserve_history':
        return `Kamino market reserve history`;
      case 'kamino_market_leverage_metrics':
        return `Kamino market leverage metrics`;
      case 'kamino_market_reserves_account':
        return `Kamino market reserves account data`;
      case 'kamino_user_rewards':
        return `Kamino K-Lend user rewards`;
      case 'kamino_loan_detail':
        return `Kamino K-Lend loan detail`;
      case 'kamino_obligation_pnl':
        return `Kamino K-Lend obligation PnL`;
      case 'kamino_obligation_metrics_history':
        return `Kamino K-Lend obligation metrics history`;
      case 'kamino_rewards_list':
        return `Kamino K-Lend rewards list`;
      case 'kamino_rewards_history':
        return `Kamino K-Lend rewards history`;
      case 'kamino_borrow_instructions':
        return `Kamino K-Lend borrow instructions`;
      case 'kamino_repay_instructions':
        return `Kamino K-Lend repay instructions`;
      case 'kamino_kswap':
        return `KSwap: ${action.params['amountIn'] ?? ''} ${action.params['tokenIn'] ?? ''} → ${action.params['tokenOut'] ?? ''}`;
      case 'kamino_deposit_instructions':
        return `Kamino K-Lend deposit instructions`;
      case 'kamino_withdraw_instructions':
        return `Kamino K-Lend withdraw instructions`;
      // ── Jito Finance Actions ───────────────────────────────────────────────────
      case 'jito_stake':
        return `Stake ${action.params['amount'] ?? ''} SOL → jitoSOL (Jito MEV Staking)`;
      case 'jito_unstake':
        return `Unstake ${action.params['amount'] ?? ''} jitoSOL → SOL`;
      case 'jito_tip':
        return `Send ${action.params['amount'] ?? ''} SOL tip for MEV protection`;
      case 'jito_bundle':
        return `Submit transaction bundle to Jito`;
      case 'jito_bundle_status':
        return `Check Jito bundle status`;
      // ── Raydium Actions ───────────────────────────────────────────────────────
      case 'raydium_swap':
        return `Swap ${action.params['amount'] ?? ''} on Raydium`;
      case 'raydium_add_liquidity':
        return `Add liquidity to Raydium pool`;
      case 'raydium_remove_liquidity':
        return `Remove liquidity from Raydium pool`;
      case 'raydium_create_pool':
        return `Create Raydium liquidity pool`;
      case 'raydium_open_position':
        return `Open concentrated liquidity position on Raydium`;
      case 'raydium_close_position':
        return `Close Raydium position`;
      case 'raydium_increase_position':
        return `Increase Raydium position`;
      case 'raydium_decrease_position':
        return `Decrease Raydium position`;
      // ── Orca Actions ───────────────────────────────────────────────────────────
      case 'orca_swap':
        return `Swap ${action.params['amount'] ?? ''} on Orca`;
      case 'orca_add_liquidity':
        return `Add liquidity to Orca Whirlpool`;
      case 'orca_remove_liquidity':
        return `Remove liquidity from Orca Whirlpool`;
      case 'orca_open_position':
        return `Open concentrated liquidity position on Orca`;
      case 'orca_close_position':
        return `Close Orca position`;
      case 'orca_increase_position':
        return `Increase Orca position`;
      case 'orca_decrease_position':
        return `Decrease Orca position`;
      case 'orca_collect_fees':
        return `Collect fees from Orca position`;
      case 'orca_collect_rewards':
        return `Collect rewards from Orca position`;
      // ── Meteora DLMM Actions ─────────────────────────────────────────────────
      case 'meteora_swap':
        return `Swap ${action.params['amount'] ?? ''} on Meteora DLMM`;
      case 'meteora_add_liquidity':
        return `Add liquidity to Meteora DLMM pool`;
      case 'meteora_remove_liquidity':
        return `Remove liquidity from Meteora position`;
      case 'meteora_create_pool':
        return `Create Meteora DLMM pool`;
      case 'meteora_open_position':
        return `Open concentrated liquidity position on Meteora`;
      case 'meteora_close_position':
        return `Close Meteora position`;
      case 'meteora_add_to_position':
        return `Add liquidity to Meteora position`;
      case 'meteora_claim_fees':
        return `Claim fees from Meteora position`;
      case 'meteora_claim_rewards':
        return `Claim rewards from Meteora position`;
      case 'meteora_stake':
        return `Stake ${action.params['amount'] ?? ''} LP tokens on Meteora farm`;
      case 'meteora_unstake':
        return `Unstake ${action.params['amount'] ?? ''} LP tokens from Meteora farm`;
      case 'meteora_harvest':
        return `Harvest rewards from Meteora farm`;
      // ── Marinade Finance Actions ─────────────────────────────────────────────────
      case 'marinade_stake':
        return `Stake ${action.params['amount'] ?? ''} SOL → mSOL (Marinade Liquid Staking)`;
      case 'marinade_unstake':
        return `Instant Unstake ${action.params['amount'] ?? ''} mSOL → SOL`;
      case 'marinade_delayed_unstake':
        return `Delayed Unstake ${action.params['amount'] ?? ''} mSOL → SOL (~2 epochs)`;
      case 'marinade_claim_ticket':
      case 'marinade_claim':
        return `Claim matured Marinade ticket → SOL`;

      // ── Solend Protocol Actions (data-only) ─────────────────────────────────────
      case 'solend_user_info':
        return `Get Solend user info`;
      case 'solend_reserves':
        return `Get Solend reserves`;
      case 'solend_market':
        return `Get Solend market info`;
      // ── Cross-Chain ───────────────────────────────────────────────────────────────
      case 'cross_chain_swap':
        return `Cross-chain swap: ${action.params['amount'] ?? ''} from chain ${action.params['originChainId'] ?? ''} to chain ${action.params['destinationChainId'] ?? ''}`;
      case 'squid_bridge':
        return `Squid bridge: ${action.params['amount'] ?? ''} ${action.params['originToken'] ?? ''} → ${action.params['destinationToken'] ?? ''} (chain ${action.params['originChainId'] ?? ''} → ${action.params['destinationChainId'] ?? ''})`;
      case 'squid_status':
        return `Squid status: ${(action.params['transactionId'] as string)?.slice(0, 12) ?? ''}…`;
      // ── Token Launch (pump.fun) ──────────────────────────────────────────────────
      case 'launch_token':
      case 'pumpfun_launch':
        return `Launch $${action.params['symbol'] ?? ''} (${action.params['name'] ?? 'token'}) on pump.fun`;
      // ── pump.fun Bonding Curve Trading ───────────────────────────────────────────
      case 'pumpfun_buy': {
        const inSol = action.params['denominatedInSol'] !== 'false';
        return `Buy ${action.params['amount'] ?? ''} ${inSol ? 'SOL of' : 'tokens of'} ${action.params['mint']?.toString().slice(0, 8) ?? ''}... on pump.fun`;
      }
      case 'pumpfun_sell': {
        const inSol = action.params['denominatedInSol'] === 'true';
        return `Sell ${action.params['amount'] ?? ''} ${inSol ? 'SOL worth of' : 'tokens of'} ${action.params['mint']?.toString().slice(0, 8) ?? ''}... on pump.fun`;
      }
      // ── pump.fun Data Queries ────────────────────────────────────────────────────
      case 'pumpfun_token_info':
        return `Token info: ${action.params['mint']?.toString().slice(0, 8) ?? ''}... on pump.fun`;
      case 'pumpfun_trending':
        return `Trending tokens on pump.fun`;
      case 'pumpfun_new':
        return `Newest launches on pump.fun`;
      case 'pumpfun_graduating':
        return `Tokens graduating to Raydium soon`;
      case 'pumpfun_search':
        return `Search pump.fun: "${action.params['query'] ?? ''}"`;
      case 'pumpfun_koth':
        return `Pump.fun King of the Hill`;
      case 'pumpfun_comments':
        return `Comments for ${action.params['mint']?.toString().slice(0, 8) ?? ''}... on pump.fun`;
      case 'pumpfun_user':
        return `Pump.fun profile: ${action.params['wallet']?.toString().slice(0, 8) ?? ''}...`;
      case 'pumpfun_bonding_curve':
        return `Bonding curve state: ${action.params['mint']?.toString().slice(0, 8) ?? ''}...`;
      default:
        return action.type;
    }
  }

  /**
   * Get icon name for an action type
   */
  getActionIcon(type: string): string {
    switch (type) {
      case 'transfer': return 'send';
      case 'swap': return 'arrow-right-left';
      case 'stake': return 'lock';
      case 'unstake': return 'unlock';
      case 'launch_token': return 'rocket';
      case 'provide_liquidity': return 'droplets';
      case 'remove_liquidity': return 'droplets';
      case 'dca': return 'repeat';
      case 'cancel_dca': return 'circle-x';
      case 'limit_order': return 'crosshair';
      case 'cancel_limit_order': return 'circle-x';
      case 'cancel_all_limit_orders': return 'trash-2';
      case 'jupsol_stake': return 'layers';
      case 'jupsol_unstake': return 'layers';
      case 'lend': return 'landmark';
      case 'withdraw_lend': return 'landmark';
      case 'borrow': return 'coins';
      case 'repay': return 'coins';
      case 'perp_open': return 'trending-up';
      case 'perp_close': return 'trending-down';
      case 'lighter_open': return 'trending-up';
      case 'lighter_close': return 'trending-down';
      case 'lighter_onboard': return 'shield-check';
      case 'lighter_deposit': return 'wallet';
      case 'lighter_leverage': return 'settings';
      case 'morpho_supply': return 'piggy-bank';
      case 'morpho_borrow': return 'hand-coins';
      case 'morpho_repay': return 'undo-2';
      case 'morpho_withdraw': return 'download';
      case 'sushi_swap': return 'arrow-down-up';
      case 'sushi_add_liquidity': return 'droplets';
      case 'jlp_add': return 'droplets';
      case 'jlp_remove': return 'droplets';
      case 'nft_buy': return 'image';
      case 'nft_list': return 'tag';
      case 'burn': return 'flame';
      case 'claim': return 'gift';
      case 'nft_mint': return 'palette';
      // SNS icons
      case 'sns_register': return 'globe';
      case 'sns_transfer': return 'send';
      case 'sns_set_record': return 'edit';
      case 'sns_delete': return 'trash';
      case 'sns_create_subdomain': return 'git-branch';
      case 'sns_list': return 'tag';
      case 'sns_buy': return 'shopping-cart';
      case 'sns_make_offer': return 'hand-coins';
      case 'sns_accept_offer': return 'check-circle';
      case 'sns_cancel_offer': return 'x-circle';
      case 'sns_p2p_create': return 'arrow-left-right';
      case 'sns_p2p_accept': return 'check-circle';
      case 'sns_p2p_cancel': return 'x-circle';
      case 'sns_set_favorite': return 'star';
      case 'sns_realloc': return 'database';
      case 'sns_transfer_subdomain': return 'send';
      case 'sns_create_record': return 'file-plus';
      case 'vote': return 'vote';
      case 'bridge': return 'cable';
      // Kamino
      case 'kamino_deposit': return 'landmark';
      case 'kamino_withdraw': return 'landmark';
      case 'kamino_borrow': return 'coins';
      case 'kamino_repay': return 'coins';
      case 'kamino_add_collateral': return 'shield-plus';
      case 'kamino_withdraw_collateral': return 'shield-minus';
      case 'kamino_multiply_open': return 'trending-up';
      case 'kamino_multiply_add': return 'plus';
      case 'kamino_multiply_withdraw': return 'minus';
      case 'kamino_multiply_close': return 'x';
      case 'kamino_long_open': return 'arrow-up-right';
      case 'kamino_short_open': return 'arrow-down-right';
      case 'kamino_position_close': return 'x';
      case 'kamino_vault_deposit': return 'vault';
      case 'kamino_vault_withdraw': return 'vault';
      case 'kamino_stake': return 'lock';
      case 'kamino_unstake': return 'unlock';
      case 'kamino_vaults': return 'list';
      case 'kamino_markets': return 'landmark';
      case 'kamino_market_reserves': return 'landmark';
      case 'kamino_user_vault_positions': return 'vault';
      case 'kamino_user_obligations': return 'file-text';
      case 'kamino_oracle_prices': return 'activity';
      case 'kamino_usd_benchmark_rates': return 'trending-up';
      case 'kamino_market_metrics_history': return 'bar-chart';
      case 'kamino_reserve_borrow_apy_history': return 'trending-up';
      case 'kamino_reserve_borrow_apy_median': return 'trending-up';
      case 'kamino_obligation_interest_earned': return 'dollar-sign';
      case 'kamino_obligation_interest_paid': return 'dollar-sign';
      case 'kamino_obligation_transactions': return 'list';
      case 'kamino_user_klend_transactions_all': return 'list';
      case 'kamino_user_klend_transactions': return 'list';
      case 'kamino_borrow_order_fills': return 'check-square';
      case 'kamino_open_borrow_orders': return 'book-open';
      case 'kamino_yield_history': return 'trending-up';
      case 'kamino_principal_token_yields': return 'percent';
      case 'kamino_airdrop_allocations': return 'gift';
      case 'kamino_airdrop_metrics': return 'bar-chart';
      case 'kamino_staking_yields': return 'layers';
      case 'kamino_staking_yields_median': return 'layers';
      case 'kamino_staking_yields_mean': return 'layers';
      case 'kamino_user_staking_boosts': return 'layers';
      case 'kamino_season_rewards_user': return 'gift';
      case 'kamino_season_rewards_vesting_pool': return 'gift';
      case 'kamino_private_credit_metrics': return 'bar-chart';
      case 'kamino_private_credit_metrics_history': return 'bar-chart';
      case 'kamino_user_farm_transactions': return 'activity';
      case 'kamino_farm_transactions': return 'activity';
      case 'kamino_vault_detail': return 'vault';
      case 'kamino_vault_metrics': return 'bar-chart';
      case 'kamino_vault_metrics_history': return 'bar-chart';
      case 'kamino_vault_allocation_history': return 'pie-chart';
      case 'kamino_vaults_rewards': return 'gift';
      case 'kamino_vaults_summary': return 'list';
      case 'kamino_vault_mint_metadata': return 'info';
      case 'kamino_vault_mint_image': return 'image';
      case 'kamino_user_metrics_history': return 'bar-chart';
      case 'kamino_user_transactions': return 'clock';
      case 'kamino_user_kvault_rewards': return 'gift';
      case 'kamino_vault_transactions': return 'list';
      case 'kamino_user_vault_position': return 'vault';
      case 'kamino_user_vault_metrics_history': return 'bar-chart';
      case 'kamino_user_vault_pnl': return 'trending-up';
      case 'kamino_user_vault_pnl_history': return 'trending-up';
      case 'kamino_vault_deposit_instructions': return 'vault';
      case 'kamino_vault_withdraw_instructions': return 'vault';
      case 'kamino_market_detail': return 'landmark';
      case 'kamino_market_reserve_history': return 'bar-chart';
      case 'kamino_market_leverage_metrics': return 'trending-up';
      case 'kamino_market_reserves_account': return 'database';
      case 'kamino_user_rewards': return 'gift';
      case 'kamino_loan_detail': return 'file-text';
      case 'kamino_obligation_pnl': return 'trending-up';
      case 'kamino_obligation_metrics_history': return 'bar-chart';
      case 'kamino_rewards_list': return 'list';
      case 'kamino_rewards_history': return 'bar-chart';
      case 'kamino_borrow_instructions': return 'code';
      case 'kamino_repay_instructions': return 'code';
      case 'kamino_kswap': return 'arrow-right-left';
      case 'kamino_deposit_instructions': return 'code';
      case 'kamino_withdraw_instructions': return 'code';
      // Jito
      case 'jito_stake': return 'zap';
      case 'jito_unstake': return 'zap-off';
      case 'jito_tip': return 'coins';
      case 'jito_bundle': return 'layers';
      case 'jito_bundle_status': return 'search';
      // Raydium
      case 'raydium_swap': return 'arrow-right-left';
      case 'raydium_add_liquidity': return 'droplets';
      case 'raydium_remove_liquidity': return 'droplets';
      case 'raydium_create_pool': return 'plus-circle';
      case 'raydium_open_position': return 'plus-square';
      case 'raydium_close_position': return 'x-square';
      case 'raydium_increase_position': return 'plus';
      case 'raydium_decrease_position': return 'minus';
      // Orca
      case 'orca_swap': return 'arrow-right-left';
      case 'orca_add_liquidity': return 'droplets';
      case 'orca_remove_liquidity': return 'droplets';
      case 'orca_open_position': return 'plus-square';
      case 'orca_close_position': return 'x-square';
      case 'orca_increase_position': return 'plus';
      case 'orca_decrease_position': return 'minus';
      case 'orca_collect_fees': return 'coins';
      case 'orca_collect_rewards': return 'gift';
      // Meteora
      case 'meteora_swap': return 'arrow-right-left';
      case 'meteora_add_liquidity': return 'droplets';
      case 'meteora_remove_liquidity': return 'droplets';
      case 'meteora_create_pool': return 'plus-circle';
      case 'meteora_open_position': return 'plus-square';
      case 'meteora_close_position': return 'x-square';
      case 'meteora_add_to_position': return 'plus';
      case 'meteora_claim_fees': return 'coins';
      case 'meteora_claim_rewards': return 'gift';
      case 'meteora_stake': return 'lock';
      case 'meteora_unstake': return 'unlock';
      case 'meteora_harvest': return 'gift';
      // Marinade
      case 'marinade_stake': return 'droplet';
      case 'marinade_unstake': return 'droplet-off';
      case 'marinade_delayed_unstake': return 'clock';
      case 'marinade_claim_ticket':
      case 'marinade_claim': return 'check-circle';
      // pump.fun — transactions
      case 'pumpfun_launch': return 'rocket';
      case 'pumpfun_buy': return 'arrow-up-circle';
      case 'pumpfun_sell': return 'arrow-down-circle';
      // pump.fun — data queries
      case 'pumpfun_token_info': return 'info';
      case 'pumpfun_trending': return 'trending-up';
      case 'pumpfun_new': return 'sparkles';
      case 'pumpfun_graduating': return 'graduation-cap';
      case 'pumpfun_search': return 'search';
      case 'pumpfun_koth': return 'crown';
      case 'pumpfun_comments': return 'message-circle';
      case 'pumpfun_user': return 'user';
      case 'pumpfun_bonding_curve': return 'chart-line';
      default: return 'zap';
    }
  }

  /**
   * Get icon name for a query type
   */
  getQueryIcon(type: string): string {
    switch (type) {
      case 'balance': return 'wallet';
      case 'price': return 'trending-up';
      case 'portfolio': return 'pie-chart';
      case 'positions': return 'layers';
      case 'transactions': return 'list';
      case 'token_info': return 'info';
      case 'trending': return 'flame';
      case 'network': return 'activity';
      case 'risk': return 'shield';
      case 'yield': return 'droplets';
      case 'analytics': return 'bar-chart-3';
      case 'nft_collection': return 'image';
      case 'airdrops': return 'gift';
      case 'gas': return 'fuel';
      case 'wallet_info': return 'wallet';
      case 'tax_report': return 'receipt-text';
      case 'dca': return 'repeat';
      case 'limit_orders': return 'clipboard-list';
      case 'lend_positions': return 'landmark';
      case 'perp_positions': return 'trending-up';
      case 'lighter_positions': return 'trending-up';
      case 'morpho_markets': return 'layers';
      case 'morpho_positions': return 'piggy-bank';
      case 'sushi_pools': return 'droplets';
      case 'alerts': return 'bell-ring';
      // Solend (data-only)
      case 'solend_user_info': return 'user';
      case 'solend_reserves': return 'database';
      case 'solend_market': return 'bar-chart';
      // Cross-chain
      case 'cross_chain_swap': return 'cable';
      case 'squid_bridge': return 'cable';
      case 'squid_status': return 'loader';
      // Meteora DLMM / DAMM
      case 'meteora_dlmm_get_pairs':
      case 'meteora_dammv2_get_pools':
      case 'meteora_dammv1_get_pools':
        return 'layers';
      // Raydium pool list
      case 'raydium_get_pools':
        return 'layers';
      case 'kamino_multiply_markets':
        return 'trending-up';
      default: return 'search';
    }
  }

  /**
   * Get a human-readable label for a query type
   */
  /** "Mad Lads — Listings" when we know the collection, "Magic Eden
   *  Listings" when we don't. */
  private static meNamed(query: ParsedQuery, subject: string): string {
    const raw = query.params?.['collectionName'] || query.params?.['symbol']
      || query.params?.['collection'] || query.params?.['collectionSymbol'];
    if (!raw || !/^[\w .-]{1,40}$/.test(String(raw))) return `Magic Eden ${subject}`;
    const pretty = String(raw).replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
    return `${pretty} — ${subject}`;
  }

  /** Protocol prefixes, longest first so `meteora_dammv2_` beats `meteora_`. */
  private static readonly QUERY_PREFIXES: ReadonlyArray<[string, string]> = [
    ['meteora_dammv2_', 'Meteora DAMM v2'],
    ['meteora_dammv1_', 'Meteora DAMM v1'],
    ['meteora_dlmm_',   'Meteora DLMM'],
    ['meteora_s2e_',    'Meteora Stake2Earn'],
    ['meteora_vault_',  'Meteora Vault'],
    ['meteora_',        'Meteora'],
    ['me_mmm_',         'Magic Eden Pools'],
    ['me_',             'Magic Eden'],
    ['orca_',           'Orca'],
    ['raydium_',        'Raydium'],
    ['kamino_',         'Kamino'],
    ['jup_',            'Jupiter'],
    ['jupiter_',        'Jupiter'],
    ['solend_',         'Solend'],
    ['jito_',           'Jito'],
    ['pumpfun_',        'pump.fun'],
    ['birdeye_',        'Birdeye'],
    ['sns_',            'SNS'],
    ['cross_chain_',    'Cross-chain'],
  ];

  /** Words that lose their meaning in Title Case. */
  private static readonly QUERY_ACRONYMS: Record<string, string> = {
    nft: 'NFT', nfts: 'NFTs', cnft: 'cNFT', sol: 'SOL', usd: 'USD',
    lp: 'LP', amm: 'AMM', clmm: 'CLMM', dlmm: 'DLMM', mmm: 'MMM',
    tvl: 'TVL', apr: 'APR', apy: 'APY', dca: 'DCA', ido: 'IDO',
    ohlcv: 'OHLCV', pnl: 'PnL', rpc: 'RPC', ata: 'ATA', id: 'ID',
    v2: 'v2', v3: 'v3', s2e: 'Stake2Earn',
  };

  /**
   * A readable name for a query type we never wrote a label for.
   *
   * The fallback used to be the identifier itself, so any card without an
   * explicit case announced itself as `me_collection_listings`. There are
   * hundreds of query types and only a few dozen have labels — the fallback
   * IS the common path, and it was showing users a variable name.
   */
  static humanizeQueryType(query: ParsedQuery): string {
    const type = query.type;
    let protocol = '';
    let rest = type;
    for (const [prefix, name] of IntentParserService.QUERY_PREFIXES) {
      if (type.startsWith(prefix)) {
        protocol = name;
        rest = type.slice(prefix.length);
        break;
      }
    }
    // `get_` is plumbing — every read gets one and it says nothing.
    rest = rest.replace(/^(get|fetch|search)_/, m => (m === 'search_' ? 'search_' : ''));

    const words = rest.split('_').filter(Boolean).map(w => {
      const lower = w.toLowerCase();
      return IntentParserService.QUERY_ACRONYMS[lower]
        ?? lower.charAt(0).toUpperCase() + lower.slice(1);
    });
    let subject = words.join(' ');

    // Name the thing being looked at when we know it — "Mad Lads — Listings"
    // beats "Magic Eden — Collection Listings" for a card about Mad Lads.
    const named = query.params?.['collectionName'] || query.params?.['symbol']
      || query.params?.['collection'] || query.params?.['collectionSymbol'];
    if (named && /^[\w .-]{1,40}$/.test(String(named))) {
      const pretty = String(named).replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase());
      subject = subject.replace(/^Collection /, '');
      return `${pretty} — ${subject}`;
    }
    if (!subject) return protocol || type;
    return protocol ? `${protocol} — ${subject}` : subject;
  }

  getQueryLabel(query: ParsedQuery): string {
    switch (query.type) {
      case 'balance':
        return query.params['token'] === 'all' ? 'All Balances' : `${query.params['token'] ?? ''} Balance`;
      case 'price':
        return `${query.params['token'] ?? 'Token'} Price`;
      case 'portfolio':
        return 'Portfolio Overview';
      case 'positions': {
        // The protocol arrives as the user typed it ("marinade"), and the card
        // header rendered it verbatim — "marinade Positions" next to every
        // other title in the app that is capitalised.
        const proto = (query.params['protocol'] ?? '').trim();
        if (!proto) return 'DeFi Positions';
        return `${proto.charAt(0).toUpperCase()}${proto.slice(1)} Positions`;
      }
      case 'lend_positions':
        return 'Jupiter Lend Positions';
      case 'perp_positions':
        return 'Jupiter Perp Positions';
      case 'lighter_positions':
        return 'Lighter Positions';
      case 'morpho_markets':
        return 'Morpho Markets';
      case 'morpho_positions':
        return 'Morpho Positions';
      case 'sushi_pools':
        return 'Sushi Pools';
      case 'transactions':
        return `Recent Transactions`;
      case 'token_info':
        return `${query.params['token'] ?? 'Token'} Info`;
      case 'trending':
        return `Trending ${query.params['category'] ?? 'Tokens'}`;
      case 'network':
        return 'Network Status';
      case 'risk':
        return 'Risk Analysis';
      case 'yield':
        return 'Yield Opportunities';
      case 'analytics':
        return `Portfolio Analytics (${query.params['period'] ?? '30d'})`;
      case 'nft_collection':
        return query.params['collection'] ? `NFTs: ${query.params['collection']}` : 'NFT Collection';
      case 'airdrops':
        return 'Airdrop Eligibility';
      case 'gas':
        return 'Network Fees';
      case 'wallet_info':
        return 'Wallet Info';
      case 'tax_report':
        return `Tax Report${query.params['year'] ? ` (${query.params['year']})` : ''}`;
      case 'dca':
        return 'DCA Orders';
      case 'limit_orders':
        return 'Limit Orders';
      case 'alerts':
        return 'Active Alerts';
      // ── Meteora DLMM / DAMM Queries ────────────────────────────────────────
      case 'meteora_dlmm_get_pairs':
        return query.params['query']
          ? `Meteora DLMM Pools (${query.params['query']})`
          : 'Meteora DLMM Pools';
      case 'meteora_dlmm_get_user_positions':
        return 'Meteora DLMM Positions';
      case 'meteora_dammv2_get_user_positions':
        return 'Meteora DAMM v2 Positions';
      // ── Uniswap (EVM LP) ──────────────────────────────────────────────────
      case 'uniswap_pools': {
        const chain = query.params['chain'] ? ` · ${query.params['chain']}` : '';
        return query.params['query']
          ? `Uniswap Pools (${query.params['query']})${chain}`
          : `Uniswap Pools${chain}`;
      }
      case 'uniswap_launches':
        return 'pools.trade Launches';
      // ── Orca Whirlpools ───────────────────────────────────────────────────
      case 'orca_get_pools':
        return query.params['token'] ? `Orca Pools (${query.params['token']})` : 'Orca Whirlpools';
      case 'orca_search_pools':
        return query.params['q'] ? `Orca Pools (${query.params['q']})` : 'Orca Whirlpools';
      case 'orca_get_user_positions':
        return 'Orca Positions';
      case 'meteora_dammv2_get_pools':
        return query.params['query']
          ? `Meteora DAMM v2 Pools (${query.params['query']})`
          : 'Meteora DAMM v2 Pools';
      case 'meteora_dammv1_get_pools':
        return query.params['query']
          ? `Meteora DAMM v1 Pools (${query.params['query']})`
          : 'Meteora DAMM v1 Pools';
      // ── Raydium Pool List ─────────────────────────────────────────────────
      case 'raydium_get_user_positions':
      case 'raydium_get_clmm_positions':
        return 'Raydium Positions';
      case 'raydium_get_pools': {
        const t = query.params['poolType'];
        const label = t === 'concentrated' ? 'Raydium CLMM Pools'
          : t === 'standard' ? 'Raydium AMM Pools'
          : 'Raydium Pools';
        return label;
      }
      // ── Kamino Multiply Pool List ─────────────────────────────────────────
      case 'kamino_multiply_markets':
        return query.params['token']
          ? `Kamino Multiply Pools (${query.params['token']})`
          : 'Kamino Multiply Pools';
      // ── Solend Protocol Queries ─────────────────────────────────────────────
      case 'solend_reserves':
        return 'Solend Reserves';
      case 'solend_market':
        return 'Solend Market Info';
      case 'solend_user_info':
        return 'Solend User Info';
      // ── Cross-Chain Queries ───────────────────────────────────────────
      case 'cross_chain_quote':
        return `Cross-Chain Quote`;
      case 'cross_chain_chains':
        return 'Supported Chains';
      case 'cross_chain_tokens':
        return 'Chain Tokens';
      // ── SNS Queries ──────────────────────────────────────────────────────────
      case 'sns_resolve':
        return `Resolve ${query.params['domain'] ?? ''}.sol`;
      case 'sns_reverse_lookup':
        return `Reverse Lookup ${(query.params['pubkey'] as string)?.slice(0, 8) ?? ''}`;
      case 'sns_domains':
        return `Domains of ${(query.params['owner'] as string)?.slice(0, 8) ?? ''}`;
      case 'sns_record':
        return `${query.params['domain'] ?? ''}.sol [${query.params['record'] ?? ''}]`;
      case 'sns_domain_info':
        return `${query.params['domain'] ?? ''}.sol Info`;
      case 'sns_check_available':
        return `${query.params['domain'] ?? ''}.sol Available?`;
      case 'sns_primary_domain':
        return `Primary Domain of ${(query.params['owner'] as string)?.slice(0, 8) ?? ''}`;
      case 'sns_subdomains':
        return `Subdomains of ${query.params['parentDomain'] ?? ''}.sol`;
      case 'sns_domain_key':
        return `Domain Key: ${query.params['domain'] ?? ''}.sol`;
      case 'sns_record_key':
        return `Record Key: ${query.params['record'] ?? ''} on ${query.params['domain'] ?? ''}.sol`;
      case 'sns_twitter_handle':
        return `Twitter Lookup: ${query.params['input'] ?? ''}`;
      // ── Magic Eden ────────────────────────────────────────────────────────
      // The humanizer below handles the rest; these are the ones where a
      // literal reading of the endpoint name ("Wallet Escrow Balance",
      // "Marketplace Popular") is not how anyone would say it.
      case 'me_wallet_escrow_balance':
        return 'Your Magic Eden Balance';
      case 'me_wallet_tokens':
      case 'me_wallet_nfts':
        return 'Your NFTs';
      case 'me_wallet_offers_made':
        return 'Offers You Made';
      case 'me_wallet_offers_received':
        return 'Offers You Received';
      case 'me_token_offers_received':
      case 'me_offers':
        return 'Offers on This NFT';
      case 'me_wallet_activities':
      case 'me_owner_activities':
        return 'Your NFT Activity';
      case 'me_token':
      case 'me_nft_info':
        return 'NFT Details';
      case 'me_collections':
        return 'Magic Eden Collections';
      case 'me_collection_leaderboard':
        return IntentParserService.meNamed(query, 'Top Traders');
      case 'me_collection_listings':
      case 'me_listings':
        return IntentParserService.meNamed(query, 'Listings');
      case 'me_collection_nfts':
        return IntentParserService.meNamed(query, 'NFTs');
      case 'me_collection_activities':
      case 'me_collection_activity':
        return IntentParserService.meNamed(query, 'Activity');
      case 'me_collection_attributes':
        return IntentParserService.meNamed(query, 'Traits');
      case 'me_collection_stats':
      case 'me_collection_info':
        return IntentParserService.meNamed(query, 'Stats');
      case 'me_mmm_pools':
        return IntentParserService.meNamed(query, 'Pools');
      default:
        return IntentParserService.humanizeQueryType(query);
    }
  }

  private parseParams(paramsStr: string): Record<string, string> {
    const params: Record<string, string> = {};
    if (!paramsStr) return params;

    // Regex to capture:
    // - angle brackets: key=<value>
    // - double quotes: key="value" (including key="" for empty strings)
    // - simple: key=value (no spaces)
    const paramRegex = /(\w+)=(?:<([^>]+)>|"([^"]*)"|(\S+))/g;
    let paramMatch: RegExpExecArray | null;

    while ((paramMatch = paramRegex.exec(paramsStr)) !== null) {
      const key = paramMatch[1];
      const value = paramMatch[2] ?? paramMatch[3] ?? paramMatch[4] ?? '';
      try {
        params[key] = decodeURIComponent(value);
      } catch {
        params[key] = value;
      }
    }

    return params;
  }

  /** Parse JSON-formatted params block: {"key": "value", ...} */
  private parseJsonParams(jsonStr: string): Record<string, string> {
    try {
      const obj = JSON.parse(jsonStr);
      return this.normalizeToStringRecord(obj);
    } catch {
      // Invalid JSON -> fall back to legacy parser
      return this.parseParams(jsonStr);
    }
  }

  /** Convert all values to strings (LLM may send number/boolean) */
  private normalizeToStringRecord(obj: Record<string, unknown>): Record<string, string> {
    const result: Record<string, string> = {};
    for (const [k, v] of Object.entries(obj)) {
      if (v === null || v === undefined) continue;
      if (typeof v === 'object') {
        result[k] = JSON.stringify(v);
      } else {
        result[k] = String(v);
      }
    }
    return result;
  }

  /**
   * Validate parsed action params — returns an array of human-readable error strings.
   * Empty array = valid. Callers can warn users or drop invalid actions.
   */
  validateActionParams(type: string, params: Record<string, string>): string[] {
    const errors: string[] = [];

    const requireParam = (key: string, label?: string) => {
      if (!params[key]?.trim()) errors.push(`Missing required param: ${label ?? key}`);
    };

    const requireNumeric = (key: string) => {
      const v = params[key];
      if (v !== undefined && isNaN(parseFloat(v))) {
        errors.push(`Param "${key}" must be a number (got: ${v})`);
      }
    };

    const requirePositive = (key: string) => {
      const v = parseFloat(params[key] ?? '');
      if (!isNaN(v) && v <= 0) {
        errors.push(`Param "${key}" must be greater than 0`);
      }
    };

    const requireAddress = (key: string) => {
      const v = params[key];
      if (v && !/^[1-9A-HJ-NP-Za-km-z]{32,44}$/.test(v)) {
        errors.push(`Param "${key}" must be a valid Solana address (got: ${v})`);
      }
    };

    const requireSlippage = (key = 'slippageBps') => {
      const v = parseFloat(params[key] ?? '');
      if (!isNaN(v) && (v < 0 || v > 10_000)) {
        errors.push(`Slippage must be between 0 and 10000 bps`);
      }
    };

    switch (type) {
      case 'swap':
      case 'limit_order':
        requireParam('inputMint'); requireAddress('inputMint');
        requireParam('outputMint'); requireAddress('outputMint');
        requireParam('amount'); requireNumeric('amount'); requirePositive('amount');
        requireSlippage();
        break;
      case 'dca':
        requireParam('inputMint'); requireParam('outputMint');
        requireParam('totalAmount'); requireNumeric('totalAmount'); requirePositive('totalAmount');
        break;
      case 'transfer':
        requireParam('to', 'recipient address'); requireAddress('to');
        requireParam('amount'); requireNumeric('amount'); requirePositive('amount');
        break;
      case 'stake':
      case 'unstake':
      case 'marinade_stake':
      case 'marinade_unstake':
      case 'marinade_delayed_unstake':
      case 'jupsol_stake':
      case 'jupsol_unstake':
        requireParam('amount'); requireNumeric('amount'); requirePositive('amount');
        break;
      case 'marinade_claim_ticket':
      case 'marinade_claim':
        requireParam('ticketAccount', 'ticket account'); requireAddress('ticketAccount');
        break;
      case 'pumpfun_buy':
      case 'pumpfun_sell':
      case 'pumpswap_buy':
      case 'pumpswap_sell':
        requireParam('mint'); requireAddress('mint');
        requireParam('amount'); requireNumeric('amount'); requirePositive('amount');
        break;
      case 'pumpfun_launch':
        requireParam('name'); requireParam('symbol'); requireParam('description');
        if (!params['imageUrl'] && !params['metadataUri']) {
          errors.push('Either imageUrl or metadataUri is required for token launch');
        }
        break;
      case 'kamino_deposit':
      case 'kamino_borrow':
        requireParam('token'); requireParam('amount');
        requireNumeric('amount'); requirePositive('amount');
        break;
    }

    return errors;
  }

  /**
   * JSON extraction with nested {} support.
   * `startIdx` = index of the opening { character in content.
   * Returns the full JSON string, or null if it cannot be parsed.
   */
  private extractBalancedJson(content: string, startIdx: number): string | null {
    let depth = 0;
    let i = startIdx;
    let inString = false;
    let escape = false;

    while (i < content.length) {
      const ch = content[i];

      if (escape) { escape = false; i++; continue; }
      if (ch === '\\' && inString) { escape = true; i++; continue; }
      if (ch === '"') { inString = !inString; i++; continue; }
      if (inString) { i++; continue; }

      if (ch === '{') depth++;
      else if (ch === '}') {
        depth--;
        if (depth === 0) return content.slice(startIdx, i + 1);
      }
      i++;
    }
    return null;
  }
}
