# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: proto/common/types.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'proto/common/types.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18proto/common/types.proto\x12\x0coprai.common\x1a\x1fgoogle/protobuf/timestamp.proto\")\n\nPagination\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\"Z\n\x11PaginatedResponse\x12\x0c\n\x04page\x18\x01 \x01(\x05\x12\r\n\x05limit\x18\x02 \x01(\x05\x12\x13\n\x0btotal_count\x18\x03 \x01(\x03\x12\x13\n\x0btotal_pages\x18\x04 \x01(\x05\"]\n\tDateRange\x12(\n\x04\x66rom\x18\x01 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12&\n\x02to\x18\x02 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x89\x01\n\x05\x45rror\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x31\n\x07\x64\x65tails\x18\x03 \x03(\x0b\x32 .oprai.common.Error.DetailsEntry\x1a.\n\x0c\x44\x65tailsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"\x07\n\x05\x45mpty*P\n\tSortOrder\x12\x1a\n\x16SORT_ORDER_UNSPECIFIED\x10\x00\x12\x12\n\x0eSORT_ORDER_ASC\x10\x01\x12\x13\n\x0fSORT_ORDER_DESC\x10\x02\x42.Z,github.com/oprai/oprai/proto/gen/go/commonpbb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'proto.common.types_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z,github.com/oprai/oprai/proto/gen/go/commonpb'
  _globals['_ERROR_DETAILSENTRY']._loaded_options = None
  _globals['_ERROR_DETAILSENTRY']._serialized_options = b'8\001'
  _globals['_SORTORDER']._serialized_start=454
  _globals['_SORTORDER']._serialized_end=534
  _globals['_PAGINATION']._serialized_start=75
  _globals['_PAGINATION']._serialized_end=116
  _globals['_PAGINATEDRESPONSE']._serialized_start=118
  _globals['_PAGINATEDRESPONSE']._serialized_end=208
  _globals['_DATERANGE']._serialized_start=210
  _globals['_DATERANGE']._serialized_end=303
  _globals['_ERROR']._serialized_start=306
  _globals['_ERROR']._serialized_end=443
  _globals['_ERROR_DETAILSENTRY']._serialized_start=397
  _globals['_ERROR_DETAILSENTRY']._serialized_end=443
  _globals['_EMPTY']._serialized_start=445
  _globals['_EMPTY']._serialized_end=452
# @@protoc_insertion_point(module_scope)
